### PR TITLE
Initial backend code

### PR DESCRIPTION
**Pull request by rodrigotassinari**
I have created two folders, one for the backend code, another for the frontend code. In the future, we may want to have two separate repos, one for the backend and another for the frontend.

I moved the original content in master (the assets) to the frontend folder.

The backend is a simple Rails application, which will host and persist the game world (board, cards, maps, units, players, etc) and serve a JSON API to the frontend code.

For now I have created the skeleton Rails app and some classes to represent the game's domain logic.

Please review and merge ASAP as to allow less conflicts.

### CODE REVIEW

**Comment by eduardohertz** [comment]
I like this, but I'd remove all HTML files from backend (layouts and public). They won't be used.

**Comment by tauil** [comment]
I liked the way you prototyped the models, but I was thinking... since this is going to be just a backend API; why not to use Sinatra instead of Rails? I also agree with @eduardohertz about the layouts.

@wpolicarpo talked with me about writing the backend in [SCALA](http://www.scala-lang.org/) but I think we could just keep working wih ruby on backend for a FAST prototype. We will already lose a lot of time learning new stuff in front-end....

**Comment by wpolicarpo** [comment]
+1 for the models.

We could try a simple rack app + grape using this modeling, maybe trying
something like Scalatra or Play in the future, just for fun.

**Comment by tauil** [comment]
:+1:

**Pull request merged**
