### PR TITLE
Adds SVG board areas

### PR DESCRIPTION
**Pull request by tauil**
Almost there... still missing the Westeros south!

The binary is from [Affinity Designer](https://affinity.serif.com/en-gb/)

### CODE REVIEW

**Comment by wpolicarpo** [comment]
@tauil before merging, let's organize folders to match the current structure we have in master

**Comment by tauil** [comment]
Roger that.

**Comment by tauil** [comment]
Done.

**Comment by tauil** [comment]
What is this? Self merge. :+1:

**Pull request merged**
